name: Articles Branch CI

on:
  pull_request:
    branches:
      - "articles/**"

jobs:
  call_reusable_workflow:
    uses: oka4shi/latex-build/.github/workflows/_build_article_branch.yml@main
    with:
      repo_name: ${{ github.repository }}
      branch_name: ${{ github.head_ref }}
      pr_url:  ${{ github.event.pull_request.html_url }}

