name: Master Branch CI

on:
  push:
    branches:
      - master

jobs:
  call_reusable_workflow:
    uses: oka4shi/latex-build/.github/workflows/_build_articles.yml@main
    with:
      repo_name: ${{ github.repository }}
      branch_name: ${{ github.ref_name }}
